<footer class="footer">
    <div class="container">
        <div class="columns">
            <div class="column is-4">
            A
            </div>
            <div class="column is-4">
            B
            </div>
            <div class="column is-4">
            C
            </div>
        </div>
    </div>
</footer>
<script type="text/javascript" src="/assets/js/script.js"></script>
</body>
</html>