<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Circolo del Re - Castelvetrano Scacchi</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
<link rel="shortcut icon" href="img/favicon.ico"/>
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
</head>
<body>

<section class="section">
    <div class="container has-text-centered">
        <a href="/">
            <img src="/assets/img/logo.png">
        </a>
        <h1 class="is-marginless">
            <a href="/">
                <span class="title is-3">
                    A.S.D. Circolo del Re
                </span>
            </a>
        </h1>
        <a href="/">
            <span class="subtitle is-4">
                Castelvetrano Scacchi
            </span>
        </a>
    </div>
</section>
