
<h2 class="title is-4">Classifica generale</h2>
<table class="table">
    <thead>
    <tr>
        <th>Pos</th>
        <th>Giocatore</th>
        <?php foreach ($standing[0]['Tournaments'] as $tournament) { ?>
            <th><?=$tournament['Date']?></th>
        <?php } ?>
        <th>Punti</th>
        <th>Bonus</th>
        <th>Totale</th>
    </tr>
    </thead>

    <tbody>
        <?php foreach ($standing[0]['Rows'] as $row) { ?>
            <tr>
                <th><?=$row['Rank']?></th>
                <td><?=$row['Name']?></td>
                <?php foreach ($standing[0]['Tournaments'] as $tournament) { ?>
                    <td><?=$row[$tournament['Time']]??'-'?></td>
                <?php } ?>
                <td><?=$row['Score']?></td>
                <td><?=$row['Bonus']?></td>
                <th><?=$row['Total']?></th>
           </tr>
        <?php } ?>
    </tbody>
</table>