<section class="hero is-light">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="columns">
                <div class="column">
                    <p class="title">
                        Chi siamo
                    </p>
                    <p class="subtitle">
                    asdasd
                    </p>
                    <p>
                        L'A.S.D. "Circolo del Re" nasce nel 2012
                    </p>
                </div>

                <div class="column">
                    prova
                </div>

            </div>
        </div>
    </div>
</section>