<div class="columns">
    <div class="column">
        <div class="card">
            <div class="card-content">
                <div class="columns">
                    <div class="column">
                        <p class="subtitle">
                            Chi siamo
                        </p>
                        <p class="subtitle">
                        asdasd
                        </p>
                        <p>
                            L'A.S.D. "Circolo del Re" nasce nel 2012
                        </p>
                        <a
                            href="/docs/assets/files/statuto-circolo-del-re-castelvetrano-scacchi.pdf"
                            target="_blank"
                            class="button is-dark">
                            <span class="icon">
                                <i class="fas fa-file-contract"></i>
                            </span>
                            <span>
                                Statuto
                            </span>
                        </a>
                        <a
                            href="/docs/assets/files/statuto-circolo-del-re-castelvetrano-scacchi.pdf"
                            target="_blank"
                            class="button is-dark">
                            <span class="icon">
                                <i class="fas fa-envelope"></i>
                            </span>
                            <span>
                                Contattaci
                            </span>
                        </a>
                    </div>

                    <div class="column">
                        <p>
                            prova
                        </p>
                        <a
                            href="https://www.facebook.com/groups/castelvetranoscacchi/"
                            target="_blank"
                            class="button is-link">
                            <span class="icon">
                                <i class="fab fa-facebook"></i>
                            </span>
                            <span>
                                Castelvetrano Scacchi
                            </span>
                        </a>
                        <a
                            href="https://lichess.org/team/asd-circolo-del-re-castelvetrano-scacchi"
                            target="_blank"
                            class="button is-success">
                            <span class="icon">
                                <i class="fas fa-chess-knight"></i>
                            </span>
                            <span>
                                Gioca Online
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

