document.write(" <ul class=\"menu\" id=\"menu\"> ");
document.write("     <li> <a href=\"#\" class=\"menulink\"> Participants </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"playersname.html\"> Sorted by Name </a> </li>" );
document.write("               <li> <a href=\"index.html\"> Sorted by Rating </a> </li>" );
document.write("               <li> <a href=\"tourstat.html\"> Statistics </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Tables </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"crosstable.html\"> Cross table by ID </a> </li>" );
document.write("               <li> <a href=\"crosstablescore.html\"> Cross table by score </a> </li>" );
document.write("               <li> <a href=\"standing.html\"> Standing </a> </li>" );
document.write("               <li> <a href=\"rankinggroup.html\"> Standing by Rtg groups </a> </li>" );
document.write("               <li> <a href=\"rankingagegroup.html\"> Standing by age groups </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Pairing </a> " );
document.write("          <ul> " );
document.write("         <li> <a href=\"pairs1.html\" > Round 1</a> </li>" );
document.write("         <li> <a href=\"pairs2.html\" > Round 2</a> </li>" );
document.write("         <li> <a href=\"pairs3.html\" > Round 3</a> </li>" );
document.write("         <li> <a href=\"pairs4.html\" > Round 4</a> </li>" );
document.write("         <li> <a href=\"pairs5.html\" > Round 5</a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("     <li> <a href=\"#\" class=\"menulink\"> Report </a> " );
document.write("          <ul> " );
document.write("               <li> <a href=\"playercard.html\"> National Player Card </a> </li>" );
document.write("          </ul> " );
document.write("     </li> " );
document.write("</ul> " );
