<?php include __DIR__.'/partials/header.phtml' ?>

<section class="section">
    <div class="container has-text-centered">
        <img src="/assets/img/logo.png">
        <h1 class="title is-marginless">
            A.S.D. Circolo del Re
        </h1>
        <span class="subtitle">Castelvetrano Scacchi</span>
        <hr/>
    </div>
</section>

<section>
    <div class="container has-text-centered">
        <?php include __DIR__.'/partials/standing.phtml' ?>
    </div>
</section>

<?php include __DIR__.'/partials/footer.phtml' ?>
