<?php include __DIR__.'/partials/header.phtml' ?>

<?php include __DIR__.'/partials/welcome.phtml' ?>

<section class="section">
    <div class="container has-text-centered">
        <?php include __DIR__.'/partials/standing.phtml' ?>
    </div>
</section>

<?php include __DIR__.'/partials/footer.phtml' ?>

<div class="columns">
    <div class="column">
        <div class="card">
            <div class="card-content">

            </div>
        </div>
    </div>
</div>